import { createCrudEndpoint } from "../../endpoints/crud-endpoint";
import type { Plugin } from "../../types/plugins";
import type { LiteralString } from "../../types/plugins";
import { generator } from "./generator";
import { logo } from "./logo";

type ScalarTheme =
	| "alternate"
	| "default"
	| "moon"
	| "purple"
	| "solarized"
	| "bluePlanet"
	| "saturn"
	| "kepler"
	| "mars"
	| "deepSpace"
	| "laserwave"
	| "none";

const getHTML = (apiReference: Record<string, any>, theme?: ScalarTheme) => `<!doctype html>
<html>
  <head>
    <title>Better CRUD API Reference</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script
      id="api-reference"
      type="application/json">
    ${JSON.stringify(apiReference)}
    </script>
	 <script>
      var configuration = {
	  	favicon: "data:image/svg+xml;utf8,${encodeURIComponent(logo)}",
	   	theme: "${theme || "default"}",
        metaData: {
			title: "Better CRUD API",
			description: "API Reference for your Better CRUD Instance",
		}
      }

      document.getElementById('api-reference').dataset.configuration =
        JSON.stringify(configuration)
    </script>
	  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`;

export interface OpenAPIOptions {
	/**
	 * The path to the OpenAPI reference page
	 *
	 * @default "/reference"
	 */
	path?: LiteralString;
	/**
	 * Disable the default reference page that is generated by Scalar
	 *
	 * @default false
	 */
	disableDefaultReference?: boolean;
	/**
	 * Theme of the OpenAPI reference page.
	 *
	 * @default "default"
	 */
	theme?: ScalarTheme;
}

export const openApiPlugin = <O extends OpenAPIOptions>(options?: O) => {
	const path = (options?.path ?? "/reference") as "/reference";

	return {
		id: "openapi",
		endpoints: {
			generateOpenAPISchema: createCrudEndpoint(
				"/openapi/schema",
				{
					method: "GET",
				},
				async (ctx) => {
					const schema = await generator(ctx.context);
					return ctx.json(schema);
				},
			),
			openAPIReference: createCrudEndpoint(
				path,
				{
					method: "GET",
				},
				async (ctx) => {
					if (options?.disableDefaultReference) {
						return ctx.json(
							{ error: "Reference UI disabled" },
							{ status: 404 },
						);
					}
					const schema = await generator(ctx.context);
					return new Response(getHTML(schema, options?.theme), {
						headers: {
							"Content-Type": "text/html",
						},
					});
				},
			),
		},
	} satisfies Plugin;
};

export type * from "./generator";
