export function layoutTemplate(withAuth: boolean): string {
	const authProviders = withAuth
		? `
import { AuthProvider } from "@/components/auth-provider";`
		: "";

	const authWrapper = withAuth
		? `
      <AuthProvider>
        {children}
      </AuthProvider>`
		: "        {children}";

	return `import type { Metadata } from "next";
import "./globals.css";${authProviders}

export const metadata: Metadata = {
  title: "Better Query App",
  description: "Generated by Better Query CLI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
${authWrapper}
      </body>
    </html>
  );
}`;
}
